src/JJMasterData.Web/Areas/MasterData/Models/ConnectionString.cs
using System.ComponentModel.DataAnnotations;
using System.Data.Common;

namespace JJMasterData.Web.Areas.MasterData.Models;

public class ConnectionString
{
    [Required] public string? Server { get; init; }

    public bool IntegratedSecurity { get; init; }

    public string? Username { get; init; }
    
    public string? Password { get; init; }

    [Required] public string? Database { get; init; }

    public string? ApplicationName { get; init; }

    public int? Timeout { get; init; }

    public bool? TrustServerCertificate { get; init; }

    public bool? Encrypt { get; init; }

    public bool? Pooling { get; init; }

    public int? MinPoolSize { get; init; }

    public int? MaxPoolSize { get; init; }

    public ConnectionString()
    {
    }

    public ConnectionString(string? connectionString)
    {
        var builder = new DbConnectionStringBuilder
        {
            ConnectionString = connectionString
        };
        if (builder.TryGetValue("data source", out var dataSource))
        {
            Server = dataSource.ToString();
        }

        if (builder.TryGetValue("user id", out var userId))
        {
            Username = userId.ToString();
        }

        if (builder.TryGetValue("password", out var password))
        {
            Password = password.ToString();
        }

        if (builder.TryGetValue("initial catalog", out var initialCatalog))
        {
            Database = initialCatalog.ToString();
        }

        if (builder.TryGetValue("application name", out var appName))
        {
            ApplicationName = appName.ToString();
        }

        if (builder.TryGetValue("integrated security", out var integratedSecurity))
        {
            IntegratedSecurity = bool.Parse(integratedSecurity.ToString()!);
        }

        if (builder.TryGetValue("trustservercertificate", out var trustServerCertificate))
        {
            TrustServerCertificate = bool.Parse(trustServerCertificate.ToString()!);
        }

        if (builder.TryGetValue("encrypt", out var encrypt))
        {
            Encrypt = bool.Parse(encrypt.ToString()!);
        }

        if (builder.TryGetValue("timeout", out var timeout))
        {
            Timeout = int.Parse(timeout.ToString()!);
        }

        if (builder.TryGetValue("pooling", out var pooling))
        {
            Pooling = bool.Parse(pooling.ToString()!);
        }

        if (builder.TryGetValue("min pool size", out var minPoolSize))
        {
            MinPoolSize = int.Parse(minPoolSize.ToString()!);
        }

        if (builder.TryGetValue("max pool size", out var maxPoolSize))
        {
            MaxPoolSize = int.Parse(maxPoolSize.ToString()!);
        }
    }


    /// <summary>
    /// Returns the string representation of a ConnectionString.
    /// </summary>
    /// <returns></returns>
    public override string ToString()
    {
        var builder = new DbConnectionStringBuilder
        {
            ["data source"] = Server,
            ["initial catalog"] = Database
        };

        if (IntegratedSecurity)
            builder["integrated security"] = true;
        else
        {
            builder["user id"] = Username;
            builder["password"] = Password;
        }

        if (ApplicationName != null)
            builder["application name"] = ApplicationName;

        if (Timeout != null)
            builder["timeout"] = Timeout;

        if (TrustServerCertificate != null)
            builder["trustservercertificate"] = TrustServerCertificate;

        if (Encrypt != null)
            builder["encrypt"] = Encrypt;

        if (Pooling != null)
            builder["pooling"] = Pooling;

        if (MinPoolSize != null)
            builder["min pool size"] = MinPoolSize;

        if (MaxPoolSize != null)
            builder["max pool size"] = MaxPoolSize;

        return builder.ToString();
    }
}

src/JJMasterData.Web/Areas/MasterData/Models/ConnectionStrings.cs
namespace JJMasterData.Web.Areas.MasterData.Models;

/// <summary>
/// Data representation of the ConnectionStrings of Microsoft.Extensions.Configuration.IConfiguration />
/// </summary>
public record ConnectionStrings
{
    public string? ConnectionString { get; set; }
}

src/JJMasterData.Web/Areas/MasterData/Models/OptionsViewModel.cs
using JJMasterData.Commons.Dao;
using JJMasterData.Commons.Options;
using JJMasterData.Core.WebComponents;

namespace JJMasterData.Web.Areas.MasterData.Models;

public class OptionsViewModel
{
    public ConnectionString ConnectionString { get; set; }
    public JJMasterDataOptions? Options { get; set; } 
    public bool IsFullscreen { get; set; }
    public string? FilePath { get; set; }
    public DataAccessProviderType ConnectionProvider { get; set; }
    public bool? IsConnectionSuccessful { get; set; }
    public bool PathExists => File.Exists(FilePath);
    public JJValidationSummary? ValidationSummary { get; set; }

    public OptionsViewModel()
    {
        ConnectionString = new ConnectionString();
    }
}

src/JJMasterData.Web/Areas/MasterData/Models/ViewModel/OptionsViewModel.cs
using JJMasterData.Commons.Dao;
using JJMasterData.Commons.Options;
using JJMasterData.Core.WebComponents;

namespace JJMasterData.Web.Areas.MasterData.Models.ViewModel;

public class OptionsViewModel
{
    public ConnectionString ConnectionString { get; set; }
    public JJMasterDataOptions? Options { get; set; } 
    public bool IsFullscreen { get; set; }
    public string? FilePath { get; set; }
    public DataAccessProviderType ConnectionProvider { get; set; }
    public bool? IsConnectionSuccessful { get; set; }
    public bool PathExists => File.Exists(FilePath);
    public JJValidationSummary? ValidationSummary { get; set; }

    public OptionsViewModel()
    {
        ConnectionString = new ConnectionString();
    }
}

src/JJMasterData.Web/Areas/MasterData/Models/ViewModels/OptionsViewModel.cs
using JJMasterData.Commons.Data;
using JJMasterData.Commons.Options;
using JJMasterData.Core.Web.Components;

namespace JJMasterData.Web.Areas.MasterData.Models.ViewModels;

public class OptionsViewModel
{
    public ConnectionString ConnectionString { get; set; }
    public JJMasterDataCommonsOptions? Options { get; set; } 
    public bool IsFullscreen { get; set; }
    public string? FilePath { get; set; }
    public DataAccessProviderType ConnectionProvider { get; set; }
    public bool? IsConnectionSuccessful { get; set; }
    public bool PathExists => File.Exists(FilePath);
    public JJValidationSummary? ValidationSummary { get; set; }

    public OptionsViewModel()
    {
        ConnectionString = new ConnectionString();
    }
}

src/JJMasterData.Web/Areas/Tools/Models/ConnectionString.cs
using System.ComponentModel.DataAnnotations;
using System.Data.Common;

namespace JJMasterData.Web.Areas.Tools.Models;

public class ConnectionString
{
    [Required] public string? Server { get; init; }

    public bool IntegratedSecurity { get; init; }

    public string? Username { get; init; }
    
    public string? Password { get; init; }

    [Required] public string? Database { get; init; }

    public string? ApplicationName { get; init; }

    public int? Timeout { get; init; }

    public bool? TrustServerCertificate { get; init; }

    public bool? Encrypt { get; init; }

    public bool? Pooling { get; init; }

    public int? MinPoolSize { get; init; }

    public int? MaxPoolSize { get; init; }

    public ConnectionString()
    {
    }

    public ConnectionString(string? connectionString)
    {
        var builder = new DbConnectionStringBuilder
        {
            ConnectionString = connectionString
        };
        if (builder.TryGetValue("data source", out var dataSource))
        {
            Server = dataSource.ToString();
        }

        if (builder.TryGetValue("user id", out var userId))
        {
            Username = userId.ToString();
        }

        if (builder.TryGetValue("password", out var password))
        {
            Password = password.ToString();
        }

        if (builder.TryGetValue("initial catalog", out var initialCatalog))
        {
            Database = initialCatalog.ToString();
        }

        if (builder.TryGetValue("application name", out var appName))
        {
            ApplicationName = appName.ToString();
        }

        if (builder.TryGetValue("integrated security", out var integratedSecurity))
        {
            IntegratedSecurity = bool.Parse(integratedSecurity.ToString()!);
        }

        if (builder.TryGetValue("trustservercertificate", out var trustServerCertificate))
        {
            TrustServerCertificate = bool.Parse(trustServerCertificate.ToString()!);
        }

        if (builder.TryGetValue("encrypt", out var encrypt))
        {
            Encrypt = bool.Parse(encrypt.ToString()!);
        }

        if (builder.TryGetValue("timeout", out var timeout))
        {
            Timeout = int.Parse(timeout.ToString()!);
        }

        if (builder.TryGetValue("pooling", out var pooling))
        {
            Pooling = bool.Parse(pooling.ToString()!);
        }

        if (builder.TryGetValue("min pool size", out var minPoolSize))
        {
            MinPoolSize = int.Parse(minPoolSize.ToString()!);
        }

        if (builder.TryGetValue("max pool size", out var maxPoolSize))
        {
            MaxPoolSize = int.Parse(maxPoolSize.ToString()!);
        }
    }


    /// <summary>
    /// Returns the string representation of a ConnectionString.
    /// </summary>
    /// <returns></returns>
    public override string ToString()
    {
        var builder = new DbConnectionStringBuilder
        {
            ["data source"] = Server,
            ["initial catalog"] = Database
        };

        if (IntegratedSecurity)
            builder["integrated security"] = true;
        else
        {
            builder["user id"] = Username;
            builder["password"] = Password;
        }

        if (ApplicationName != null)
            builder["application name"] = ApplicationName;

        if (Timeout != null)
            builder["timeout"] = Timeout;

        if (TrustServerCertificate != null)
            builder["trustservercertificate"] = TrustServerCertificate;

        if (Encrypt != null)
            builder["encrypt"] = Encrypt;

        if (Pooling != null)
            builder["pooling"] = Pooling;

        if (MinPoolSize != null)
            builder["min pool size"] = MinPoolSize;

        if (MaxPoolSize != null)
            builder["max pool size"] = MaxPoolSize;

        return builder.ToString();
    }
}

src/JJMasterData.Web/Areas/Tools/Models/ConnectionStrings.cs
namespace JJMasterData.Web.Areas.Tools.Models;

/// <summary>
/// Data representation of the ConnectionStrings of Microsoft.Extensions.Configuration.IConfiguration />
/// </summary>
public record ConnectionStrings
{
    public string? ConnectionString { get; set; }
}

src/JJMasterData.Web/Areas/Tools/Models/OptionsViewModel.cs
using JJMasterData.Commons.Data;
using JJMasterData.Commons.Options;
using JJMasterData.Core.Web.Components;

namespace JJMasterData.Web.Areas.Tools.Models;

public class OptionsViewModel
{
    public ConnectionString ConnectionString { get; set; }
    public JJMasterDataCommonsOptions? Options { get; set; } 
    public bool IsFullscreen { get; set; }
    public string? FilePath { get; set; }
    public DataAccessProviderType ConnectionProvider { get; set; }
    public bool? IsConnectionSuccessful { get; set; }
    public bool PathExists => File.Exists(FilePath);
    public JJValidationSummary? ValidationSummary { get; set; }

    public OptionsViewModel()
    {
        ConnectionString = new ConnectionString();
    }
}

src/JJMasterData.Web/Areas/MasterData/Controllers/OptionsController.cs
using JJMasterData.Web.Areas.MasterData.Models.ViewModels;
using JJMasterData.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace JJMasterData.Web.Areas.MasterData.Controllers;

public class OptionsController : MasterDataController
{
    private OptionsService Service { get; }
    
    public OptionsController(OptionsService service)
    {
        Service = service;
    }
    
    public async Task<IActionResult> Index(bool isFullscreen=false)
    {
        var viewModel = await Service.GetViewModel(isFullscreen);
        
        return View(viewModel);
    }
    
    public async Task<IActionResult> Save(OptionsViewModel model)
    {

        await Service.SaveOptions(model);

        if (!ModelState.IsValid)
        {
            model.ValidationSummary = Service.GetValidationSummary();
        }
        
        return View(nameof(Index), model);
    }
    
    public async Task<IActionResult> TestConnection(OptionsViewModel model)
    {
        if (ModelState.IsValid)
        {
            var result = await OptionsService.GetConnectionResultAsync(model.ConnectionString.ToString());
            model.IsConnectionSuccessful = result.IsConnectionSuccessful;

            if (!result.IsConnectionSuccessful.GetValueOrDefault())
            {
                ModelState.AddModelError(nameof(OptionsViewModel.ConnectionString),result.ErrorMessage!);
            }

            model.ValidationSummary = Service.GetValidationSummary();
        }

        return View(nameof(Index), model);
    }
}

src/JJMasterData.Web/Areas/Tools/Controllers/OptionsController.cs
using JJMasterData.Web.Areas.MasterData.Controllers;
using JJMasterData.Web.Areas.Tools.Models;
using JJMasterData.Web.Services;
using Microsoft.AspNetCore.Mvc;

namespace JJMasterData.Web.Areas.Tools.Controllers;

public class OptionsController : ToolsController
{
    private OptionsService Service { get; }
    
    public OptionsController(OptionsService service)
    {
        Service = service;
    }
    
    public async Task<IActionResult> Index(bool isFullscreen=false)
    {
        var viewModel = await Service.GetViewModel(isFullscreen);
        
        return View(viewModel);
    }
    
    public async Task<IActionResult> Save(OptionsViewModel model)
    {

        await Service.SaveOptions(model);

        if (!ModelState.IsValid)
        {
            model.ValidationSummary = Service.GetValidationSummary();
        }
        
        return View(nameof(Index), model);
    }
    
    public async Task<IActionResult> TestConnection(OptionsViewModel model)
    {
        if (ModelState.IsValid)
        {
            var result = await OptionsService.GetConnectionResultAsync(model.ConnectionString.ToString());
            model.IsConnectionSuccessful = result.IsConnectionSuccessful;

            if (!result.IsConnectionSuccessful.GetValueOrDefault())
            {
                ModelState.AddModelError(nameof(OptionsViewModel.ConnectionString),result.ErrorMessage!);
            }

            model.ValidationSummary = Service.GetValidationSummary();
        }

        return View(nameof(Index), model);
    }
}

src/JJMasterData.Web/Areas/MasterData/Views/Options/Index.cshtml
@using JJMasterData.Core.DataDictionary
@using JJMasterData.Core.Web.Components
@using JJMasterData.Web.Extensions
@using JJMasterData.Web.TagHelpers
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model JJMasterData.Web.Areas.MasterData.Models.ViewModels.OptionsViewModel

@{
    Layout = "_MasterDataLayout.Popup";
}

<form>
    <input asp-for="FilePath" hidden="hidden"/>
    <input asp-for="IsFullscreen" hidden="hidden"/>

    @if (Model.IsFullscreen)
    {
        <jj-title title="Application Settings"/>
    }

    @if (Model.PathExists)
    {
        <jj-alert icon="InfoCircle"
                  color="Info"
                  message="@Model.FilePath"
                  title="All changes will be saved in the file located at the path:"/>
    }
    
    @if (Model is { IsConnectionSuccessful:true })
    {
        <jj-alert
            title="Success"
            message="Connection successfully estabilished."
            icon="@IconType.CheckCircle"
            color="@PanelColor.Success"/>
    }

    @if (!ViewData.ModelState.IsValid)
    {
        @Model.ValidationSummary?.GetHtmlString()
    }

    <jj-collapse-panel
        title="Connection String"
        partial="_ConnectionString"
        model="Model"
        icon="@IconType.Connectdevelop"/>

    <div class="row">
        <div class="col-sm-12">
            @if (Model.IsFullscreen)
            {
                <jj-link-button 
                    url-action="/en-us/DataDictionary/" 
                    icon="Home" 
                    text="Home"/>
            }
            <jj-link-button type="LinkButtonType.Submit" 
                            url-action="@Url.Action("Save", "Options")" 
                            icon="Save" 
                            text="Save"/>
        </div>
    </div>


</form>

src/JJMasterData.Web/Areas/MasterData/Views/Options/_ConnectionString.cshtml
@using JJMasterData.Commons.Data
@using JJMasterData.Commons.Localization
@using JJMasterData.Core.Web
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model JJMasterData.Web.Areas.MasterData.Models.ViewModels.OptionsViewModel

<div class="@BootstrapHelper.FormGroup">
    <div class="row">
        <div class="col-sm-3">
            <label asp-for="ConnectionProvider" class="@BootstrapHelper.Label"></label><span class="required-symbol">*</span>
            <select asp-items="@Html.GetEnumSelectList<DataAccessProviderType>()" asp-for="ConnectionProvider" class="form-control form-select">
            </select>
            <span asp-validation-for="ConnectionProvider" class="text-danger"></span>
        </div>
        <div class="col-sm-7">
            <label asp-for="ConnectionString.Server" class="@BootstrapHelper.Label"></label><span class="required-symbol">*</span>
            <input asp-for="ConnectionString.Server" class="form-control"/>
            <span asp-validation-for="ConnectionString.Server" class="text-danger"></span>
        </div>
        <div class="col-sm-2">
            <label asp-for="ConnectionString.Timeout" class="@BootstrapHelper.Label"></label>
            <input asp-for="ConnectionString.Timeout" class="form-control"/>
            <span asp-validation-for="ConnectionString.Timeout" class="text-danger"></span>
        </div>
        <div class="col-sm-12">
            <label asp-for="ConnectionString.IntegratedSecurity" class="@BootstrapHelper.Label"></label><span class="required-symbol">*</span>
            <select onchange="onIntegratedSecurityChange(this.value)" asp-for="ConnectionString.IntegratedSecurity" class="form-control form-select">
                <option value="False">False</option>
                <option value="True">True</option>
            </select>
            <span asp-validation-for="ConnectionString.IntegratedSecurity" class="text-danger"></span>
        </div>

        <div class="row" id="login-data" style="display: @(Model.ConnectionString.IntegratedSecurity ? "none" : "flex")">
            <div class="col-sm-6">
                <label asp-for="ConnectionString.Username" class="@BootstrapHelper.Label"></label><span class="required-symbol">*</span>
                <input asp-for="ConnectionString.Username" class="form-control"/>
                <span asp-validation-for="ConnectionString.Username" class="text-danger"></span>
            </div>
            <div class="col-sm-6">
                <label asp-for="ConnectionString.Password" class="@BootstrapHelper.Label"></label><span class="required-symbol">*</span>
                <input asp-for="ConnectionString.Password" class="form-control"/>
                <span asp-validation-for="ConnectionString.Password" class="text-danger"></span>
            </div>
        </div>

        <div class="col-sm-6">
            <label asp-for="ConnectionString.Database" class="@BootstrapHelper.Label"></label><span class="required-symbol">*</span>
            <input asp-for="ConnectionString.Database" class="form-control"/>
            <span asp-validation-for="ConnectionString.Database" class="text-danger"></span>
        </div>
        <div class="col-sm-6">
            <label asp-for="ConnectionString.ApplicationName" class="@BootstrapHelper.Label"></label>
            <input asp-for="ConnectionString.ApplicationName" class="form-control"/>
            <span asp-validation-for="ConnectionString.ApplicationName" class="text-danger"></span>
        </div>
        <div class="col-sm-6">
            <label asp-for="ConnectionString.TrustServerCertificate" class="@BootstrapHelper.Label"></label>
            <select asp-for="ConnectionString.TrustServerCertificate" class="form-control form-select">
                <option value="False">False</option>
                <option value="True">True</option>
            </select>
            <span asp-validation-for="ConnectionString.TrustServerCertificate" class="text-danger"></span>
        </div>
        <div class="col-sm-6">
            <label asp-for="ConnectionString.Encrypt" class="@BootstrapHelper.Label"></label>
            <select asp-for="ConnectionString.Encrypt" class="form-control form-select">
                <option value="False">False</option>
                <option value="True">True</option>
            </select>
            <span asp-validation-for="ConnectionString.Encrypt" class="text-danger"></span>
        </div>
        <div class="col-sm-4">
            <label asp-for="ConnectionString.Pooling" class="@BootstrapHelper.Label"></label>
            <select asp-for="ConnectionString.Pooling" class="form-control form-select">
                <option value="False">False</option>
                <option value="True">True</option>
            </select>
            <span asp-validation-for="ConnectionString.Pooling" class="text-danger"></span>
        </div>
        <div class="row" id="pooling-data">
            <div class="col-sm-4">
                <label asp-for="ConnectionString.MinPoolSize" class="@BootstrapHelper.Label"></label>
                <input asp-for="ConnectionString.MinPoolSize" class="form-control"/>
                <span asp-validation-for="ConnectionString.MinPoolSize" class="text-danger"></span>
            </div>
            <div class="col-sm-4">
                <label asp-for="ConnectionString.MaxPoolSize" class="@BootstrapHelper.Label"></label>
                <input asp-for="ConnectionString.MaxPoolSize" class="form-control"/>
                <span asp-validation-for="ConnectionString.MaxPoolSize" class="text-danger"></span>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <button class="@BootstrapHelper.DefaultButton" formaction="@Url.Action("TestConnection", "Options")" type="submit"><span class="fa fa-chain"></span>&nbsp;@Translate.Key("Test Connection")</button>
    </div>
</div>


<script type="text/javascript">
    function onIntegratedSecurityChange(value) {
        if (value === "True"){
            document.getElementById("login-data").style.display="none";
        }
        else{
            document.getElementById("login-data").style.display="flex";
        }
    }
</script>